steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/dystomarket/stock-simulator:$SHORT_SHA'
      - '-f'  # Specify the Dockerfile
      - 'Dockerfile.simulate'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/dystomarket/stock-simulator:$SHORT_SHA']
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "dystomarket"
      - "--image"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "dystomarket-cloud-run@$PROJECT_ID.iam.gserviceaccount.com"
      - "--add-cloudsql-instances"
      - "$PROJECT_ID:europe-west1:dystomarket"
      - "--set-secrets=DB_USER=db_user:latest,DB_PASSWORD=db_password:latest,DB_NAME=db_name:latest,DB_HOST=db_host:latest"
      - "--set-env-vars"
      - "NEXT_PUBLIC_API_URL=https://dystomarket.paulooze.com"
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY