steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "dystomarket"
      - "--image"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "dystomarket-cloud-run@$PROJECT_ID.iam.gserviceaccount.com"
      - "--set-secrets=DB_USER=db_user:latest,DB_PASSWORD=db_password:latest,DB_NAME=db_name:latest,DB_HOST=db_host:latest"
      - "--set-env-vars=DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASSWORD}@localhost/${_DB_NAME}?host=${_DB_HOST}"
      - "--set-env-vars"
      - "NEXT_PUBLIC_API_URL=https://dystomarket-936117578615.europe-west1.run.app"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "services"
      - "update"
      - "dystomarket"
      - "--region"
      - "europe-west1"
      - "--add-cloudsql-instances"
      - "$PROJECT_ID:europe-west1:dystomarket-db"
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/dystomarket:$SHORT_SHA"
options:
  logging: CLOUD_LOGGING_ONLY
