steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "dystomarket"
      - "--image"
      - "$LOCATION-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA"
      - "--region"
      - "$LOCATION"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "dystomarket-cloud-run@$PROJECT_ID.iam.gserviceaccount.com" # Use your service account email
      - "--set-env-vars=DATABASE_URL=postgresql://$$DB_USER:$$DB_PASSWORD@/$$DB_NAME?host=$$DB_HOST" # Construct DATABASE_URL
      - "--set-env-vars"
      - "NEXT_PUBLIC_API_URL=https://dystomarket-936117578615.europe-west10.run.app"
    secretEnv: ["DB_USER", "DB_PASSWORD", "DB_NAME", "DB_HOST"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "services"
      - "update"
      - "dystomarket"
      - "--region"
      - "$LOCATION"
      - "--add-cloudsql-instances"
      - "$PROJECT_ID:$LOCATION:dystomarket-db" # Your instance connection name
images:
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/dystomarket:$SHORT_SHA"
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/db_user/versions/latest
      env: DB_USER
    - versionName: projects/$PROJECT_ID/secrets/db_password/versions/latest
      env: DB_PASSWORD
    - versionName: projects/$PROJECT_NUMBER/secrets/db_name/versions/latest
      env: DB_NAME
    - versionName: projects/$PROJECT_NUMBER/secrets/db_host/versions/latest
      env: DB_HOST
