steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west10-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west10-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "dystomarket"
      - "--image"
      - "europe-west10-docker.pkg.dev/$PROJECT_ID/dystomarket/dystomarket:$SHORT_SHA"
      - "--region"
      - "europe-west10"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--service-account"
      - "dystomarket-cloud-run@$PROJECT_ID.iam.gserviceaccount.com"
      - "--set-secrets=DB_USER=projects/$PROJECT_NUMBER/secrets/db_user/versions/latest,DB_PASSWORD=projects/$PROJECT_NUMBER/secrets/db_password/versions/latest,DB_NAME=projects/$PROJECT_NUMBER/secrets/db_name/versions/latest,DB_HOST=projects/$PROJECT_NUMBER/secrets/db_host/versions/latest"
      - "--set-env-vars=DATABASE_URL=postgresql://$$DB_USER:$$DB_PASSWORD@/$$DB_NAME?host=$$DB_HOST"
      - "--set-env-vars"
      - "NEXT_PUBLIC_API_URL=https://dystomarket-936117578615.europe-west10.run.app"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "services"
      - "update"
      - "dystomarket"
      - "--region"
      - "europe-west10"
      - "--add-cloudsql-instances"
      - "$PROJECT_ID:europe-west10:dystomarket-db"
images:
  - "europe-west10-docker.pkg.dev/$PROJECT_ID/dystomarket:$SHORT_SHA"
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
