version: "3.8"
services:
  db:
    image: postgres:15-alpine # Or your preferred PostgreSQL version
    restart: always # Restart the container if it fails
    ports:
      - "5432:5432" # Expose PostgreSQL port (host:container) - access on localhost:5432
    environment:
      POSTGRES_USER: user # Replace with your desired username
      POSTGRES_PASSWORD: password # Replace with a strong password
      POSTGRES_DB: fake_stocks # Replace with your desired database name
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data to a named volume
  redis:
    image: redis:latest
    container_name: dystomarket-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - redis_data:/data


volumes:
  db_data:
  redis_data:
