version: "3.8"
services:
  db:
    image: postgres:15-alpine # Or your preferred PostgreSQL version
    restart: always # Restart the container if it fails
    ports:
      - "5432:5432" # Expose PostgreSQL port (host:container) - access on localhost:5432
    environment:
      POSTGRES_USER: user # Replace with your desired username
      POSTGRES_PASSWORD: password # Replace with a strong password
      POSTGRES_DB: fake_stocks # Replace with your desired database name
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data to a named volume

volumes:
  db_data: # Define the named volume for data persistence
