/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as CompanyTickerSymbolImport } from './routes/company/$tickerSymbol'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CompanyTickerSymbolRoute = CompanyTickerSymbolImport.update({
  id: '/company/$tickerSymbol',
  path: '/company/$tickerSymbol',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/company/$tickerSymbol': {
      id: '/company/$tickerSymbol'
      path: '/company/$tickerSymbol'
      fullPath: '/company/$tickerSymbol'
      preLoaderRoute: typeof CompanyTickerSymbolImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/company/$tickerSymbol': typeof CompanyTickerSymbolRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/company/$tickerSymbol': typeof CompanyTickerSymbolRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/company/$tickerSymbol': typeof CompanyTickerSymbolRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/register' | '/company/$tickerSymbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/register' | '/company/$tickerSymbol'
  id: '__root__' | '/' | '/about' | '/register' | '/company/$tickerSymbol'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RegisterRoute: typeof RegisterRoute
  CompanyTickerSymbolRoute: typeof CompanyTickerSymbolRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RegisterRoute: RegisterRoute,
  CompanyTickerSymbolRoute: CompanyTickerSymbolRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/register",
        "/company/$tickerSymbol"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/company/$tickerSymbol": {
      "filePath": "company/$tickerSymbol.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
