name: Deploy API
on:
  push:
    tags:
      - 'api-v*'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DO Registry
        run: echo "${{ secrets.DO_ACCESS_TOKEN }}" | docker login -u "oauth2" --password-stdin registry.digitalocean.com
      - name: Build and Push API Image
        run: |
          docker buildx build -t registry.digitalocean.com/dystohub/dystomarket-api:latest -f Dockerfile.api . --push