name: Deploy API & AI News
on:
  push:
    tags:
      - 'ai-news-v*'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DO Registry
        run: echo "${{ secrets.DO_ACCESS_TOKEN }}" | docker login -u "oauth2" --password-stdin registry.digitalocean.com
      - name: Build and Push API Image
        run: |
          docker build -t ${{ secrets.DO_REGISTRY }}/dystomarket-api:{{ github.ref }} -f Dockerfile.ai-news
          docker push ${{ secrets.DO_REGISTRY }}/dystomarket-ai-news:{{ github.ref }}