name: Deploy AI News
on:
  push:
    tags:
      - 'ai-news-v*'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DO Registry
        run: echo "${{ secrets.DO_ACCESS_TOKEN }}" | docker login -u "oauth2" --password-stdin registry.digitalocean.com
      - name: Build and Push API Image
        run: |
          docker buildx build \
            --tag registry.digitalocean.com/dystohub/dystomarket-ai-news:latest \
            --tag registry.digitalocean.com/dystohub/dystomarket-ai-news:sha-$(git rev-parse --short HEAD) \
            -f Dockerfile.ai-news . --load
      - name: Push AI News Image
        run: |
          docker push registry.digitalocean.com/dystomarket-ai-news:latest
          docker push registry.digitalocean.com/dystomarket-ai-news:sha-$(git rev-parse --short HEAD)
